version: '3.5'

services:
  web:
    image: nginx
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
       - 80:80
    restart: always

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5431:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    container_name: db_button

  redis:
      image: redis:latest
      restart: unless-stopped 

  backend:
    image: logger
    container_name: backend
    environment:
      - DB_HOST=db_button
      - DB_PORT=5431
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - REDIS=redis 
      - REDIS_PORT=6379
      - FRONT_URL=http://localhost:5000
    expose:
      - 80
    depends_on: 
      - db
      - web

  frontend:
    image: frontend
    container_name: frontend
    expose:
      - 80
    environment:
      - API_URL=http://localhost:8000

