# The file after optimization. 
# Image size is now only 87.9MB.

FROM node:alpine as builder

WORKDIR /usr/src/app

RUN adduser -D app

COPY --chown=app:app . /usr/src/app

RUN npm i && \
    npm run build

USER app

FROM node:8.9.4

COPY --from=builder  /usr/src/app/build/ /build/

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "-l", "3000", "build"]

