# The file after optimization. 
# Image size is now only 87.9MB.

FROM node:alpine as builder

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN npm i && \
    npm run build

FROM node:alpine

RUN adduser -D app

COPY --from=builder --chown=app:app  /usr/src/app/build/ /build/

RUN npm install -g serve

EXPOSE 3000

USER app

CMD ["serve", "-s", "-l", "3000", "build"]

