version: '3.5'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5431:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    container_name: db_button

  redis:
      image: redis:latest
      restart: unless-stopped 

  backend:
    image: logger
    environment:
      - DB_HOST=db_button
      - DB_PORT=5431
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - REDIS=redis 
      - REDIS_PORT=6379
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:8000
    depends_on: 
      - db

  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
