version: '3.5'

services:

  backend:
    image: km_backend
    environment: 
      - FRONT_URL=http://localhost:3000
    ports: 
      - 5000:5000
    volumes: 
      - model:/src/model
    depends_on:
      - training

  frontend:
    image: km_frontend
    environment:
      - API_URL=http://localhost:5000
    ports:
      - 3000:3000
 
  training: 
    image: km_training  
    volumes: 
      - model:/src/model
      - images:/src/imgs
      - data:/src/data

volumes:
  model:
  images: 
  data:
  
